### ISSUE TITLE
Tracking issue for Rust issues and feature requests

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/nitrokey-3-firmware#510]
This is a list of issues with the compiler or the standard library that we encountered during firmware development and features that would be helpful for firmware development and that we want to keep track of.

## Bugs / Problems

- [ ] Unnecessary copies leading to doubled or tripled stack usage
  - examples / more details:
    - https://github.com/trussed-dev/iso7816/pull/20
    - https://github.com/trussed-dev/ctaphid-dispatch/pull/6
  - not reported yet
- [ ] `expect` messages are still present in the final binary because `core::result::unwrap_failed` is `#[inline(never)]`
  - not reported yet

## Features

- [ ] deny non-exhaustive use of non-exhaustive enum
  - https://github.com/rust-lang/rust-clippy/issues/11890
  - https://github.com/rust-lang/rust/issues/89554
- [ ] `optimize_for_size` std lib feature
  - https://github.com/rust-lang/rust/issues/125612
- [ ] `build-std`/``panic_immediate_abort`
